openapi: 3.0.0
info:
  title: QuestionAPI
  version: 0.0.0
tags: []
paths:
  /questions:
    get:
      operationId: listMultipleChoiceQuestions
      description: Get all questions
      parameters:
        - name: difficulty
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/Models.MultipleChoiceQuestionDifficulty'
          explode: false
        - name: category
          in: query
          required: false
          schema:
            type: string
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Models.MultipleChoiceQuestionSet'
  /questions/{id}:
    get:
      operationId: getMultipleChoiceQuestion
      description: Get a question by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Models.MultipleChoiceQuestion'
components:
  schemas:
    Models.MultipleChoiceOption:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: string
        text:
          type: string
      description: Multiple choice option
    Models.MultipleChoiceQuestion:
      type: object
      required:
        - id
        - question
        - options
        - correctAnswer
        - type
      properties:
        id:
          type: string
          format: uuid
        question:
          type: string
        options:
          type: array
          items:
            $ref: '#/components/schemas/Models.MultipleChoiceOption'
        correctAnswer:
          $ref: '#/components/schemas/Models.MultipleChoiceOption'
        type:
          $ref: '#/components/schemas/Models.MultipleChoiceQuestionType'
      description: Multiple choice question
    Models.MultipleChoiceQuestionDifficulty:
      type: string
      enum:
        - Easy
        - Medium
        - Hard
      description: Difficulty for trivia questions
    Models.MultipleChoiceQuestionSet:
      type: object
      required:
        - questions
      properties:
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Models.MultipleChoiceQuestion'
      description: Multiple choice question set
    Models.MultipleChoiceQuestionType:
      type: string
      enum:
        - Standard
        - Opinion
      description: Question type for multiple choice questions
