openapi: 3.0.0
info:
  title: QuestionAPI
  version: 0.0.0
tags: []
paths:
  /questions:
    get:
      operationId: listQuestions
      description: Get all questions
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Models.Question'
  /questions/{id}:
    get:
      operationId: getQuestion
      description: Get a question by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Models.Question'
components:
  schemas:
    Models.MultipleChoiceOption:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: string
        text:
          type: string
      description: Multiple choice option
    Models.MultipleChoiceQuestion:
      type: object
      required:
        - question
        - options
        - correctAnswer
      properties:
        question:
          type: string
        options:
          type: array
          items:
            $ref: '#/components/schemas/Models.MultipleChoiceOption'
        correctAnswer:
          $ref: '#/components/schemas/Models.MultipleChoiceOption'
      description: Multiple choice question
    Models.MultipleChoiceQuestionSet:
      type: object
      required:
        - questions
      properties:
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Models.MultipleChoiceQuestion'
      description: Multiple choice question set
    Models.Question:
      type: object
      required:
        - id
        - text
        - options
        - correctAnswer
      properties:
        id:
          type: string
          format: uuid
        text:
          type: string
        options:
          type: array
          items:
            type: string
        correctAnswer:
          type: string
      description: A trivia question.
